- hosts: ec2_instances
  connection: local
  gather_facts: false
  tasks:
    - name: Launch Instance
      ec2:
        group_id: "{{ hostvars[inventory_hostname].group_id }}"
        count: 1
        instance_type: 'm3.medium'
        image: '{{ hostvars[inventory_hostname].image }}'
        wait: true
        region: 'us-east-1'
        #keypair: '{{ keypair }}'
        aws_access_key: "{{ aws_access_key|default(lookup('env', 'AWS_ACCESS_KEY')) }}"
        aws_secret_key: "{{ aws_secret_key|default(lookup('env', 'AWS_SECRET_KEY')) }}"
        instance_tags: "{{ hostvars[inventory_hostname].tags }}"
      register: ec2

    - name: Wait for SSH
      wait_for:
        host: "{{ item['instances'][0]['public_ip'] }}"
        port: 22
        delay: 10
        timeout: 320
        state: started
      with_items: ec2.results

    - name: Wait a little longer for centos
      pause: seconds=20